version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet clean src\IX.Versioning.sln -c Release

    dotnet clean src\IX.Versioning.sln -c Debug

    dotnet restore src/IX.Versioning.sln

    cd src\IX.CsprojVersioning\

    dotnet csprojVersioning dotnet-csprojVersioning.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Versioning\

    dotnet csprojVersioning IX.Versioning.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Versioning.Csproj\

    dotnet csprojVersioning IX.Versioning.Csproj.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Versioning.NuSpec\

    dotnet csprojVersioning IX.Versioning.NuSpec.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\..\

    dotnet clean src\IX.Versioning.sln -c Release

    dotnet clean src\IX.Versioning.sln -c Debug

    dotnet restore src/IX.Versioning.sln
build:
  project: src\IX.Versioning.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: src\IX.Versioning\bin\Release\IX.Versioning.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Versioning
- path: src\IX.CsprojVersioning\bin\Release\dotnet-csprojVersioning.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.CsprojVersioning
- path: src\IX.Versioning.NuSpec\bin\Release\IX.Versioning.NuSpec.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Versioning.NuSpec
- path: src\IX.Versioning.Csproj\bin\Release\IX.Versioning.Csproj.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Versioning.Csproj
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package
  api_key:
    secure: eF0Mu+Ky+FtngFJN7u4unv9l2ebEvlvfim9hPpWkRAc=
  skip_symbols: true